package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"main/graph/model"
	"main/internal/database"
)

// GetUser is the resolver for the getUser field.
func (r *queryResolver) AuthUser(ctx context.Context, email string) (*model.AuthUser, error) {
	users := &database.User{}
	user := r.DB.GetUser(email)
	return &model.AuthUser{
		ID:           &user.ID,
		Email:        &user.Email,
		HashPassword: &users.HashPassword,
		Role:         &users.Role,
		Version:      &users.Version,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
