// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthUser struct {
	ID           *int32  `json:"id,omitempty"`
	Email        *string `json:"email,omitempty"`
	HashPassword *string `json:"hashPassword,omitempty"`
	Role         *string `json:"role,omitempty"`
	Version      *int32  `json:"version,omitempty"`
}

type Query struct {
}
