// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type UserAuthResult struct {
	Email        string  `json:"email"`
	HashPassword string  `json:"hash_password"`
	Role         *string `json:"role,omitempty"`
}
